index_1.html
htmlacademy-htmlcss/1867559-sedona-32 pull request #2
Opened 2021-09-26 17:19 UTC by LizPavets

Я целеноправлено создала другую папку и сохранила туда, html-структуру главной страницы. Если ты не против)

2021-09-27 08:35 UTC, juliettasav requested changes
Оставила комменты по коду.

2021-09-27 08:35 UTC, juliettasav commented on index_1.html
> +    <header class="page-header">
тут тоже можно назвать просто `header`, т.к. никаких хедеров на странице у тебя нет в разметке

2021-09-27 08:35 UTC, juliettasav commented on index_1.html
> +                        <span class="visually-hidden">
этот элемент не скрыт на странице – скрывается блок, которые ты пока что не добавляла согласно дз
по поиску это иконка, то есть `<img>`, спан здесь не уместен

2021-09-27 08:35 UTC, juliettasav commented on index_1.html
> +                <b>и мы покажем вам лучшие предложения гостиниц в Седоне</b>
тег `<b>` это тег, которые меняет начертание шрифта со стандартного, например с 400, до bold, то есть 700
по макету если перенос, но изменения на жирный шрифт не вижу, проверь макет, пожалуйста

2021-09-27 08:35 UTC, juliettasav commented on index_1.html
> +              <p class="newsletter-email">
`<p>` – это тег для абзацов, текстов или других шрифтовых элементов, но в основном это контент и текст
В твоем случае лежит поле для заполнение имейла, поэтому лучше поменять эту оббертку-тег, на другое, в данному случае на `<div>`

2021-09-27 17:48 UTC, LizPavets commented on index_1.html
> +                    <a class="navigation-link" href="maim.html">Главная</a>
изменила))

2021-09-27 17:49 UTC, LizPavets commented on index_1.html
> +                    <a class="navigation-link" href="about.html">О Седоне</a>
создала файлы

2021-09-27 17:51 UTC, LizPavets commented on index_1.html
> +            <h2 class="header-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
поменяла на класс headline-title

2021-09-27 17:56 UTC, LizPavets commented on index_1.html
> +            <p class="advantages-description">Седона - не аттракцион для туристов, там течёт своя жизнь</p>
не совсем поняла как правильно делать табулярность в строках, но вроде исправила!!!!

2021-09-27 18:01 UTC, LizPavets commented on index_1.html
> +            <h2 class="visually-hidden">Поиск гостиниц в Седоне</h2>
кажется с ctrl+c я немного перебрала)) Исправила

2021-09-27 18:01 UTC, LizPavets commented on index_1.html
> +    <footer class="page-footer">
ок

2021-09-27 18:03 UTC, LizPavets commented on index_1.html
> +            <h2 class="visually-hidden">Социальные сети</h2>
это надписи нет на макете, но я же сделала ее скрытой и указала, чтобы было понятно, что это за ссылки. Как название категории. Так не правильно?

2021-09-27 18:04 UTC, LizPavets commented on index_1.html
> +    <header class="page-header">
ок

2021-09-27 18:05 UTC, LizPavets commented on index_1.html
> +                <b>и мы покажем вам лучшие предложения гостиниц в Седоне</b>
блин это я хотела перенос сделать. Нужно было тег <br> использовать. Исправила

2021-09-28 07:34 UTC, juliettasav approved these changes

2021-09-28 07:34 UTC, juliettasav commented on index.html
> +        <img alt="Добро пожаловать в Седону" src="" >
Я не уверена на счет этого макета (пока оставим так).
Скорее всего там одна текстовая картинка, и h1 скрыт как эллемент, но текст какой-то добавляется. Я еще это уточню, и мы дальше уже это разберем) Пока что пусть будет так

2021-09-28 07:34 UTC, juliettasav commented on index.html
> +                    <h3 class="advantages-title">Настоящий городок</h3>
`advantages-item-title`

2021-09-28 07:34 UTC, juliettasav commented on index.html
> +          <h2 class="headline-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
`advantages-title` лучше, ведь у тебя секция `advantages`, а что такое headline не особо понятно

2021-09-28 07:34 UTC, juliettasav commented on index.html
> +            <p class="footer-made-about-text">.html
тут будет картинка, пока оставим так

2021-09-28 07:34 UTC, juliettasav commented on index.html
> +                <br>academy</br>
<br> это одиночный тег, то есть можно ставить <br /> – и все, это воспринимается как перенос, поесть: 
`<p class="footer-made-about-text">.html<br /> academy </p>`

2021-09-28 07:35 UTC, merged

2021-09-28 08:02 UTC, juliettasav commented on catalog.html
> +               <br><a href="#" class="product-card-button button">Подробнее</a>
`<br>` !

2021-09-28 08:02 UTC, juliettasav commented on catalog.html
> +        <h2 class="page-title">Подпишитесь на рассылку</h2>
`newsletter-title`

2021-09-28 08:02 UTC, juliettasav commented on catalog.html
> +        <p class="title">Только полезная информация и никакого спама, честное бойскаутское!</p>
`newsletter-description`

2021-09-28 10:00 UTC, LizPavets commented on index.html
> +          <h2 class="headline-title">Седона — небольшой городок в Аризоне, заслуживающий большего!</h2>
исправила

2021-09-28 10:00 UTC, LizPavets commented on index.html
> +                    <h3 class="advantages-title">Настоящий городок</h3>
исправила

2021-09-28 10:00 UTC, LizPavets commented on index.html
> +                <br>academy</br>
исправила

2021-09-28 10:00 UTC, LizPavets commented on catalog.html
> +              <label class="catalog-filter-label"></label>
какой тег?

2021-09-28 10:00 UTC, LizPavets commented on catalog.html
> +              <br><button class="range-toggle toggle-min" type="button">
исправила

2021-09-28 10:00 UTC, LizPavets commented on catalog.html
> +               <br><a href="#" class="product-card-button button">Подробнее</a>
исправила